### ISSUE TITLE
move tagline below logo

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/new-website#15]
I added the logo but the tag line floats right and i haven't figured out how to put it below our logo image. Hence ticket :)

**Comment by semioticrobotic** [comment]
What do ya'll think about just axing the tagline altogether? Truthfully, I put it there mostly as a placeholder (and for SEO purposes). If we've got the tag in the site's `meta`, do we need it on-page? I'm fine to just eliminate.

**Comment by semioticrobotic** [comment]
On a phone call, @LauraHilliger and I agreed to the above strategy. :point_up:
