### ISSUE TITLE
Each volume in book series needs its own landing page

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/new-website#3]
Our `Books` page looks great, but our next step should be to give each volume in the series its own discrete page.

**Comment by semioticrobotic** [comment]
I think this is captured in #12?

**Comment by LauraHilliger** [comment]
LOL

**Comment by LauraHilliger** [comment]
sorry, I was laughing because I *just* updated the other ticket, these pages all exist now

**Comment by semioticrobotic** [comment]
Yay! Thank you.
