### ISSUE TITLE
Header graphics should be full-bleed

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/new-website#4]
Our template works best with full-bleed header graphics, and we should use those. But we need to create them.

**Comment by LauraHilliger** [comment]
https://github.com/open-organization/new-website/commit/6866c08da7065fc06006f25ae88dd21035a2af0f

**Comment by LauraHilliger** [comment]
ALSO - FWIW you need to double check that the icons you use from font awesome are the free icons. If copying icon code from font awesome's site, they don't filter unless you actually click "free". The book page icon wasn't showing up and it took me a good long while to understand why :)

**Comment by semioticrobotic** [comment]
Dude. This looks *amazing*. This is precisely what I was imagining when we were chatting. **Thank you** for taking this on. :pray:
