### ISSUE TITLE
Embed Meet the Ambassadors playlist to the About page

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/new-website#8]
We have some videos of ambassadors introducing themselves:
https://www.youtube.com/playlist?list=PLLIYDJHuxOkZ91IGhRf7gQb74_PuMUI83

**Comment by LauraHilliger** [comment]
https://github.com/open-organization/new-website/commit/841104d3d6be76e412c210ec96bdbca3dea83b64

**Comment by semioticrobotic** [comment]
Great use of pre-existing resources. Love it.
